DROP TABLE IF EXISTS users, items, booking, requests, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(64),
  email varchar(64)
);

CREATE TABLE IF NOT EXISTS items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(64),
  description varchar(256),
  available bool,
  user_id integer,
  request_id integer
);

CREATE TABLE IF NOT EXISTS booking (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date timestamp,
  end_date timestamp,
  item_id integer,
  booker_id integer,
  status varchar(64)
);

CREATE TABLE IF NOT EXISTS requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar(256),
  user_id integer,
  create_date timestamp
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text varchar(256),
  item_id integer,
  author_id integer,
  created timestamp
);

ALTER TABLE users ADD CONSTRAINT EMAIL_UNIQUE UNIQUE(email);

ALTER TABLE items ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE booking ADD FOREIGN KEY (item_id) REFERENCES items (id);

ALTER TABLE booking ADD FOREIGN KEY (booker_id) REFERENCES users (id);

ALTER TABLE requests ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE comments ADD FOREIGN KEY (item_id) REFERENCES items (id);

ALTER TABLE comments ADD FOREIGN KEY (author_id) REFERENCES users (id);